trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  dockerHubUsername: elynfoo
  imageName: devops-flaskapp
  imageTag: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: BuildPush
        displayName: Build and Push to Docker Hub
        steps:
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: build
              dockerfile: Dockerfile
              repository: $(dockerHubUsername)/$(imageName)
              tags: |
                $(imageTag)
                latest

          - task: Docker@2
            displayName: Push to Docker Hub
            inputs:
              command: push
              containerRegistry: DockerHubConnection
              repository: $(dockerHubUsername)/$(imageName)
              tags: |
                $(imageTag)
                latest

  - stage: Deploy
    displayName: Deploy to Kubernetes
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Apply Kubernetes Manifests
        steps:
          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes
            inputs:
              action: deploy
              manifests: |
                k8s/deployment.yaml
                k8s/service.yaml
              containers: $(dockerHubUsername)/$(imageName):$(imageTag)
