trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: Default

variables:
  imageName: elynfoo/devops-flaskapp

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: BuildPush
        displayName: Build and Push to Docker Hub
        steps:
          - script: |
              docker logout
              echo $(DOCKER_PASSWORD)| docker login -u "$(DOCKER_USERNAME)" --password-stdin
              docker build -t $(imageName):$(Build.BuildId) -t $(imageName):latest .
              docker push $(imageName):$(Build.BuildId)
              docker push $(imageName):latest
            displayName: Build and Push to Docker Hub

  - stage: Deploy
    displayName: Deploy to Kubernetes
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy to minikube
        steps:
          - powershell: |
              $env:KUBECONFIG = "C:\agent\kube.config"
              kubectl config use-context minikube
              if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
              kubectl set image deployment/flask-portfolio flask-portfolio=$(imageName):$(Build.BuildId) -n default
              if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
              kubectl rollout status deployment/flask-portfolio -n default --timeout=120s
            displayName: Update Kubernetes Deployment
