apiVersion: v1
kind: Secret
metadata:
  name: flask-db-secret
type: Opaque
stringData:
  POSTGRES_USER: flaskuser
  POSTGRES_PASSWORD: flaskpass
  POSTGRES_DB: flaskapp
  DATABASE_URL: postgresql://flaskuser:flaskpass@postgres-service:5432/flaskapp
